spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        pool:
          type: fixed
          max-connections: 500
          acquire-timeout: 45000

sentinel:
  eager:
    enabled: true
  transport:
    dashboard: localhost:8858
  metrics:
    enabled: true
  filter:
    enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
